DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
    id IDENTITY NOT NULL PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    registered_date DATE NOT NULL
);

DROP TABLE IF EXISTS TOPIC;
CREATE TABLE TOPIC (
    id IDENTITY NOT NULL PRIMARY KEY,
    author_id INTEGER NOT NULL REFERENCES PERSON(id),
    text VARCHAR(400) not NULL,
    published_date DATE NOT NULL
);

DROP TABLE IF EXISTS ARGUMENT;
CREATE TABLE ARGUMENT (
    id IDENTITY NOT NULL PRIMARY KEY,
    is_for BOOLEAN NOT NULL,
    author_id INTEGER NOT NULL REFERENCES PERSON(id),
    topic_id INTEGER NOT NULL REFERENCES TOPIC(id),
    text VARCHAR(MAX) NOT NULL,
    published_date DATE NOT NULL
);
